version: '3.0'

services:
  app:
    image: address-book:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NPM_AUTH_TOKEN
    ports:
      - 8088:8088
    volumes:
      - ./src:/home/node/src
# Uncomment the following when developing integration tests
# tests:
#   image: address-book:test
#   build:
#     context: .
#     dockerfile: Dockerfile.test
#     args:
#       - NPM_AUTH_TOKEN
#   environment:
#     - NODE_CONFIG_ENV
#   command: npm run integration:local -- --watchAll
#   volumes:
#     - ./test/integration:/home/node/test/integration
