log:
  encryptionKey: LOGS_ENCRYPTION_KEY
services:
  akamaiAuthToken: AKAMAI_PASSTHROUGH
  fullyQualifiedClientId: IDENTITY_CLIENT_ID
  identity:
    username: IDENTITY_USERNAME
    password: IDENTITY_PASSWORD
